/* Auto-generated by teacherinfo.html - do not edit by hand. */
var G = window.G = window.G || {};
G.TEACHER_INFO = {
 "m-todd":{
  "teaches":"Assistant Principal",
  "job":"Assistant Principal"
 },
 "m-walker":{
  "teaches":"All Subjects",
  "job":"Principal"
 },
 "m-nurse":{
  "teaches":"",
  "job":"Nurse"
 },
 "m-front":{
  "teaches":"",
  "job":"School Secretary"
 },
 "m-caf":{
  "teaches":"",
  "job":"Cafeteria Manager"
 },
 "custom-1":{
  "teaches":"",
  "job":"Family Resource Center Coordinator"
 },
 "t-205":{
  "teaches":"",
  "job":"Guidance Counselor"
 },
 "t-212":{
  "teaches":"",
  "job":"Reading Intervention Teacher"
 },
 "t-217":{
  "teaches":"All Subjects",
  "job":"Teacher"
 },
 "t-219":{
  "teaches":"4th Grade / 5th Grade",
  "job":"Social Studies"
 },
 "t-220":{
  "teaches":"4th / 5th Grade",
  "job":"Math"
 },
 "t-221":{
  "teaches":"All",
  "job":"Art"
 },
 "t-222":{
  "teaches":"4th / 5th Grade",
  "job":"Science"
 },
 "t-223":{
  "teaches":"4th / 5th Grade",
  "job":"Reading"
 },
 "t-224":{
  "teaches":"Kindergarten",
  "job":"Teacher"
 },
 "t-225":{
  "teaches":"Kindergarten",
  "job":"Kindergarten"
 },
 "b-gym":{
  "teaches":"PE",
  "job":"PE Teacher"
 },
 "b-music":{
  "teaches":"All Subjects",
  "job":"PE"
 },
 "b-dance":{
  "teaches":"Dance / Drama",
  "job":"Dance Drama Teacher"
 },
 "t-216":{
  "teaches":"",
  "job":"Special Education Teacher"
 }
};
