#!/usr/bin/env python3
"""Ashland dev server: static files + the room editor's SAVE endpoint.

Run with:  python3 serve.py
Then play at http://localhost:8123 and edit rooms at http://localhost:8123/roomeditor.html
"""
import http.server
import json
import pathlib

ROOT = pathlib.Path(__file__).parent
OVERRIDES_FILE = ROOT / "js" / "room-overrides.js"
PORT = 8123


class Handler(http.server.SimpleHTTPRequestHandler):
    def do_POST(self):
        if self.path == "/api/save-rooms":
            try:
                length = int(self.headers.get("Content-Length", 0))
                data = json.loads(self.rfile.read(length))
                # new payload: {"rooms": {...}, "teacherNames": {...}};
                # old payload (rooms only) still accepted
                rooms = data.get("rooms", data)
                names = data.get("teacherNames", {})
                sprites = data.get("teacherSprites", {})
                customs = data.get("customRooms", {})
                content = (
                    "/* Auto-generated by roomeditor.html - do not edit by hand. */\n"
                    "var G = window.G = window.G || {};\n"
                    "G.ROOM_OVERRIDES = " + json.dumps(rooms, separators=(",", ":")) + ";\n"
                    "G.TEACHER_NAME_OVERRIDES = " + json.dumps(names, separators=(",", ":")) + ";\n"
                    "G.TEACHER_SPRITE_OVERRIDES = " + json.dumps(sprites, separators=(",", ":")) + ";\n"
                    "G.CUSTOM_ROOMS = " + json.dumps(customs, separators=(",", ":")) + ";\n"
                )
                if OVERRIDES_FILE.exists():
                    (ROOT / "js" / "room-overrides.bak").write_text(OVERRIDES_FILE.read_text())
                OVERRIDES_FILE.write_text(content)
                self.send_response(200)
                self.send_header("Content-Type", "text/plain")
                self.end_headers()
                self.wfile.write(b"ok")
                print(f"  saved {len(rooms)} room(s) + {len(names)} name(s) -> js/room-overrides.js")
            except Exception as exc:  # noqa: BLE001
                self.send_response(500)
                self.end_headers()
                self.wfile.write(str(exc).encode())
        elif self.path == "/api/save-signs":
            try:
                length = int(self.headers.get("Content-Length", 0))
                data = json.loads(self.rfile.read(length))
                content = (
                    "/* Auto-generated by signeditor.html - do not edit by hand. */\n"
                    "var G = window.G = window.G || {};\n"
                    "G.SIGN_OVERRIDES = " + json.dumps(data, separators=(",", ":")) + ";\n"
                )
                (ROOT / "js" / "sign-overrides.js").write_text(content)
                self.send_response(200)
                self.send_header("Content-Type", "text/plain")
                self.end_headers()
                self.wfile.write(b"ok")
                print(f"  saved sign positions -> js/sign-overrides.js")
            except Exception as exc:  # noqa: BLE001
                self.send_response(500)
                self.end_headers()
                self.wfile.write(str(exc).encode())
        elif self.path == "/api/save-sprites":
            # rewrite ONLY the sprite line of room-overrides.js (rooms untouched)
            try:
                import re
                length = int(self.headers.get("Content-Length", 0))
                data = json.loads(self.rfile.read(length))
                sprites = data.get("sprites", data)
                src = OVERRIDES_FILE.read_text()
                new_line = "G.TEACHER_SPRITE_OVERRIDES = " + json.dumps(sprites, separators=(",", ":")) + ";\n"
                new_src, n = re.subn(r"G\.TEACHER_SPRITE_OVERRIDES = .*?;\n", lambda m: new_line, src, count=1, flags=re.S)
                if n != 1:
                    raise RuntimeError("sprite line not found in room-overrides.js")
                (ROOT / "js" / "room-overrides.bak").write_text(src)
                OVERRIDES_FILE.write_text(new_src)
                self.send_response(200)
                self.send_header("Content-Type", "text/plain")
                self.end_headers()
                self.wfile.write(b"ok")
                print(f"  saved {len(sprites)} teacher look(s) -> js/room-overrides.js")
            except Exception as exc:  # noqa: BLE001
                self.send_response(500)
                self.end_headers()
                self.wfile.write(str(exc).encode())
        elif self.path == "/api/save-teacher-info":
            try:
                length = int(self.headers.get("Content-Length", 0))
                data = json.loads(self.rfile.read(length))
                content = (
                    "/* Auto-generated by teacherinfo.html - do not edit by hand. */\n"
                    "var G = window.G = window.G || {};\n"
                    "G.TEACHER_INFO = " + json.dumps(data, separators=(",", ":"), indent=1) + ";\n"
                )
                (ROOT / "js" / "teacher-info.js").write_text(content)
                self.send_response(200)
                self.send_header("Content-Type", "text/plain")
                self.end_headers()
                self.wfile.write(b"ok")
                print(f"  saved teacher info for {len(data)} room(s) -> js/teacher-info.js")
            except Exception as exc:  # noqa: BLE001
                self.send_response(500)
                self.end_headers()
                self.wfile.write(str(exc).encode())
        else:
            self.send_response(404)
            self.end_headers()

    def end_headers(self):
        # always serve fresh files while developing
        self.send_header("Cache-Control", "no-store")
        super().end_headers()


if __name__ == "__main__":
    import os

    os.chdir(ROOT)
    print(f"Ashland dev server: http://localhost:{PORT}  (editor: /roomeditor.html)")
    http.server.ThreadingHTTPServer(("", PORT), Handler).serve_forever()
